# Basic Numpy

In [78]:
# Create an 1d array from a list
import numpy as np
list1 = [1,2,3,4,5,6]
arr1 = np.array(list1)
print(arr1)
print(type(arr1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [79]:
# Add 2 to each element of arr1d
arr1 + 2

array([3, 4, 5, 6, 7, 8])

In [80]:
# Create an 1d array from a list of list
list2 = [[1,2,3], [4,5,6], [7,8,0]]
arr2 = np.array(list2)
print(arr2)
print(type(arr2))

# Create a float 2d array
arr2f = np.array(list2, dtype='float')
print(arr2f)

# Create a string 2d array
arr2s = np.array(list2, dtype='str')
print(arr2s)

# Create a bool 2d array
arr2b = np.array(list2, dtype='bool')
print(arr2b)

# Convert to 'int' datatype
arr2i = arr2f.astype('int')
print(arr2i)

[[1 2 3]
 [4 5 6]
 [7 8 0]]
<class 'numpy.ndarray'>
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 0.]]
[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '0']]
[[ True  True  True]
 [ True  True  True]
 [ True  True False]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]


In [81]:
# Create an object array to hold numbers as well as strings
listo = [1,2,'a','b']
arro = np.array(listo, dtype='object')
print(arro)
print(type(arro))

# convert array back to list
listo1 = arro.tolist()
print(listo1)
print(type(listo1))

[1 2 'a' 'b']
<class 'numpy.ndarray'>
[1, 2, 'a', 'b']
<class 'list'>


In [82]:
# inspect size and shape of an array

# If it is a 1D or a 2D array or more
print(arr1.ndim)
print(arr2.ndim)
print(arro.ndim)

# How many items are present in each dimension
print(arr1.shape)
print(arr2.shape)

# What is the total number of items in it
print(arr1.size)
print(arr2.size)

1
2
1
(6,)
(3, 3)
6
9


In [83]:
# how to extract specific items or portion in array
list2 = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]
arr2 = np.array(list2, dtype='float')
print(arr2)
# Extract the first 2 rows and columns
arr2[:1, :1]

# Get the boolean output by applying the condition to each element.
b = arr2 > 4
print(b)

arr2[b]

[[1. 2. 3. 4.]
 [3. 4. 5. 6.]
 [5. 6. 7. 8.]]
[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


array([5., 6., 5., 6., 7., 8.])

In [84]:
# Reverse only the row positions
print(arr2[::-1, ])

# Reverse the row and column positions
print(arr2[::-1, ::-1])
print(arr2)

[[5. 6. 7. 8.]
 [3. 4. 5. 6.]
 [1. 2. 3. 4.]]
[[8. 7. 6. 5.]
 [6. 5. 4. 3.]
 [4. 3. 2. 1.]]
[[1. 2. 3. 4.]
 [3. 4. 5. 6.]
 [5. 6. 7. 8.]]


In [85]:
# Insert a nan and an inf
print(arr2[1,1])
print(arr2[1,2])
arr2[1,1] = np.nan  # not a number
arr2[1,2] = np.inf  # infinite

# Replace nan and inf with -1. Don't use arr2 == np.nan
missing_bool = np.isnan(arr2) | np.isinf(arr2)
print(missing_bool)
arr2[missing_bool] = -1  
print(arr2)

4.0
5.0
[[False False False False]
 [False  True  True False]
 [False False False False]]
[[ 1.  2.  3.  4.]
 [ 3. -1. -1.  6.]
 [ 5.  6.  7.  8.]]


In [75]:
# mean, max and min
print("Mean ", arr2.mean())
print("Max ", arr2.max())
print("Min ", arr2.min())

print("Mean row wsie ", arr2.mean(axis=1))
print("Mean column wise ", arr2.mean(axis=0))

# cumulutive sum
print(np.cumsum(arr2))

Mean  3.5833333333333335
Max  8.0
Min  -1.0
Mean row wsie  [2.5  1.75 6.5 ]
Mean column wise  [3.         2.33333333 3.         6.        ]
[ 1.  3.  6. 10. 13. 12. 11. 17. 22. 28. 35. 43.]


In [87]:
# Assign portion of arr2 to arr2a. Doesn't really create a new array.
arr2a = arr2[:2,:2]  
print(arr2a)
print(arr2a[:1, :1])
arr2a[:1, :1] = 100  # 100 will reflect in arr2
print(arr2)

# Copy portion of arr2 to arr2b
arr2b = arr2[:2, :2].copy()
arr2b[:1, :1] = 101  # 101 will not reflect in arr2
arr2

[[100.   2.]
 [  3.  -1.]]
[[100.]]
[[100.   2.   3.   4.]
 [  3.  -1.  -1.   6.]
 [  5.   6.   7.   8.]]


array([[100.,   2.,   3.,   4.],
       [  3.,  -1.,  -1.,   6.],
       [  5.,   6.,   7.,   8.]])

In [91]:
# Flatten it to a 1d array
arr2flatten = arr2.flatten()
print(arr2flatten)
print(arr2)

arr2ravel = arr2.ravel()
arr2ravel[4] = 300
print(arr2ravel)
print(arr2)


[100.   2.   3.   4.   3.  -1.  -1.   6.   5.   6.   7.   8.]
[[100.   2.   3.   4.]
 [  3.  -1.  -1.   6.]
 [  5.   6.   7.   8.]]
[100.   2.   3.   4. 300.  -1.  -1.   6.   5.   6.   7.   8.]
[[100.   2.   3.   4.]
 [300.  -1.  -1.   6.]
 [  5.   6.   7.   8.]]


In [98]:
# Lower limit is 0 be default
np.arange(10)

# 0 to 19
np.arange(0,20)

# 0 to 19 with step of 2
np.arange(0,20, 2)

# 0 to 19 decresing order step as -2
np.arange(20,0,-2)

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [116]:
# you want to create an array of exactly 10 numbers between 1 and 50, Can you compute what would be the step value?
# Start at 1 and end at 50
print(np.linspace(start=1, stop=52, num=10, dtype=float))
print(np.linspace(start=1, stop=52, num=13, dtype=int))

# Start at 10^1 and end at 10^50
np.logspace(start=1, stop=50, num=10, base=10) 

np.zeros([2,3])
np.ones([3,4])


[ 1.          6.66666667 12.33333333 18.         23.66666667 29.33333333
 35.         40.66666667 46.33333333 52.        ]
[ 1  5  9 13 18 22 26 30 35 39 43 47 52]


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [121]:
a = [[1,2,3],[4,5,6]]
np.tile(a,3)
print(a)
np.repeat(a,4)

[[1, 2, 3], [4, 5, 6]]


array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6,
       6, 6])

In [133]:
# Generate Random Numbers between 0 and 1 
# or
# Normal distribution with mean=0 and variance=1 of shape 2,2
print(np.random.rand(2,2))

# Random integers between [0, 10) of shape 2,2
print(np.random.randint(2,6,size=[2,5]))
print(np.random.randint(2,6,size=[15]))

[[0.59982462 0.02961984]
 [0.71563601 0.71979837]]
[[5 2 2 2 3]
 [4 4 3 2 2]]
[5 2 5 4 2 4 3 4 3 4 5 4 4 5 2]


In [141]:
# Pick 10 items from a given list, with equal probability
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10))  

# Pick 10 items from a given list with a predefined probability 'p'
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10, p=[0.3, .1, 0.1, 0.4, 0.1])) 

['u' 'i' 'e' 'i' 'u' 'o' 'o' 'e' 'a' 'a']
['o' 'o' 'i' 'a' 'a' 'a' 'i' 'a' 'o' 'a']


In [151]:
# Create the Random State
rn = np.random.RandomState(10)

# create random numbers between 0 and 2 with shape 2,2
print(rn.rand(2,2))

# OR

# Create the random seed
np.random.seed(11)

print(np.random.rand(2,2))

[[0.77132064 0.02075195]
 [0.63364823 0.74880388]]
[[0.18026969 0.01947524]
 [0.46321853 0.72493393]]


In [152]:
# Unique Items and count
# Create random integers of size 10 between [0,10)
np.random.seed(100)
arr_rand = np.random.randint(0, 10, size=10)
print(arr_rand)

# Get the unique items and their counts
uniqs, counts = np.unique(arr_rand, return_counts=True)
print("Unique items : ", uniqs)
print("Counts       : ", counts)

[8 8 3 7 7 0 4 2 5 2]
Unique items :  [0 2 3 4 5 7 8]
Counts       :  [1 2 1 1 1 2 2]


# Advanced Numpy

In [153]:
# Getindex location that satisfy a given condition
# Create an array
import numpy as np
arr_rand = np.array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2])
print("Array: ", arr_rand)

Array:  [8 8 3 7 7 0 4 2 5 2]


In [156]:
# Positions where value > 5
index_gt5 = np.where(arr_rand > 5)
print("Positions where value > 5: ", index_gt5)
# Take items at given index
print(arr_rand.take(index_gt5))

# Take items at given index
arr_rand.take(np.where(arr_rand < 5))

Positions where value > 5:  (array([0, 1, 3, 4], dtype=int64),)
[[8 8 7 7]]


array([[3, 0, 4, 2, 2]])

In [161]:
# Find location of Max and Min values
print("Max value postion = ", np.argmax(arr_rand))
print("Min value postion = ", np.argmin(arr_rand))

Max value postion =  0
Min value postion =  5


In [175]:
# Turn off scientific notation
np.set_printoptions(suppress=True)  

# Import data from csv file url
path = 'https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv'
data = np.genfromtxt(path, delimiter=',', skip_header=1, filling_values=-999, dtype=None)
data[:3]  # see first 3 rows

C:\Users\vaibhav.javadekar\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:6: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


array([(18., 8, 307., 130, 3504, 12. , 70, 1, b'"chevrolet chevelle malibu"'),
       (15., 8, 350., 165, 3693, 11.5, 70, 1, b'"buick skylark 320"'),
       (18., 8, 318., 150, 3436, 11. , 70, 1, b'"plymouth satellite"')],
      dtype=[('f0', '<f8'), ('f1', '<i4'), ('f2', '<f8'), ('f3', '<i4'), ('f4', '<i4'), ('f5', '<f8'), ('f6', '<i4'), ('f7', '<i4'), ('f8', 'S38')])

In [183]:
# Concatenate 2 numpy arrays columnwise and rowwise

a = np.zeros([4, 4])
b = np.ones([4, 4])
print(a)
print(b)

print(np.concatenate([a,b], axis=1))
#np.hstack((a,b))
np.r_[a,b]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]]


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [221]:
# Sort numpy array based on one or more columns

# Sort 2d array based on 1st column
rn = np.random.RandomState(100)
arr = rn.randint(1,6,size=[8,4])
#arr = rn.random.randint(1,6,size=[8,4])
print(arr)



[[1 1 4 1]
 [3 5 3 3]
 [3 3 2 1]
 [1 5 4 5]
 [3 1 4 2]
 [3 4 5 5]
 [2 4 5 5]
 [4 4 4 2]]


In [243]:
#np.sort(arr, axis = 0)
sort_index = np.argsort(arr, axis=0)
print(sort_index)

# Ascending Order based on 1 column only
print(arr[sort_index[::,0]])

# Desceinding Order based on 1 column only
print(arr[sort_index[::-1,0]])


[[0 0 2 0]
 [3 4 1 2]
 [6 2 0 4]
 [1 5 3 7]
 [2 6 4 1]
 [4 7 7 3]
 [5 1 5 5]
 [7 3 6 6]]
[[1 1 4 1]
 [1 5 4 5]
 [2 4 5 5]
 [3 5 3 3]
 [3 3 2 1]
 [3 1 4 2]
 [3 4 5 5]
 [4 4 4 2]]
[[4 4 4 2]
 [3 4 5 5]
 [3 1 4 2]
 [3 3 2 1]
 [3 5 3 3]
 [2 4 5 5]
 [1 5 4 5]
 [1 1 4 1]]


In [245]:
# Ascending Order based on 2 column only
print(arr[sort_index[::,1]])
print("---------------------")
# Desceinding Order based on 2 column only
print(arr[sort_index[::-1,1]])

[[1 1 4 1]
 [3 1 4 2]
 [3 3 2 1]
 [3 4 5 5]
 [2 4 5 5]
 [4 4 4 2]
 [3 5 3 3]
 [1 5 4 5]]
---------------------
[[1 5 4 5]
 [3 5 3 3]
 [4 4 4 2]
 [2 4 5 5]
 [3 4 5 5]
 [3 3 2 1]
 [3 1 4 2]
 [1 1 4 1]]


In [246]:
# Dates in Numpy
# Create a datetime64 object
date64 = np.datetime64('2018-02-04 23:10:10')
date64

numpy.datetime64('2018-02-04T23:10:10')

In [248]:
# Create date sequence
dates = np.arange(np.datetime64('2018-02-01'), np.datetime64('2018-02-10'))
print(dates)
np.is_busday(dates)

['2018-02-01' '2018-02-02' '2018-02-03' '2018-02-04' '2018-02-05'
 '2018-02-06' '2018-02-07' '2018-02-08' '2018-02-09']


array([ True,  True, False, False,  True,  True,  True,  True,  True])

In [251]:
# Advance Numpy Functions

# Define a scalar function
def foo(x):
    if x % 2 == 1:
        return x**2
    else:
        return x/2

# On a scalar
print('x = 10 returns ', foo(10))
print('x = 11 returns ', foo(11))    

# On a vector, doesn't work
#print('x = [10, 11, 12] returns ', foo([10, 11, 12]))  # Error 

fooVectorized = np.vectorize(foo)
fooVectorized([10,12,13,14])

x = 10 returns  5.0
x = 11 returns  121


array([  5.,   6., 169.,   7.])

In [255]:
# Apply a function column wise or row wise

print(arr)

# Row wise
np.apply_along_axis(fooVectorized, axis = 1, arr=arr)

[[1 1 4 1]
 [3 5 3 3]
 [3 3 2 1]
 [1 5 4 5]
 [3 1 4 2]
 [3 4 5 5]
 [2 4 5 5]
 [4 4 4 2]]


array([[ 1,  1,  2,  1],
       [ 9, 25,  9,  9],
       [ 9,  9,  1,  1],
       [ 1, 25,  2, 25],
       [ 9,  1,  2,  1],
       [ 9,  2, 25, 25],
       [ 1,  2, 25, 25],
       [ 2,  2,  2,  1]])

In [256]:
# Find the location to insert so the array will remain sorted

x = np.arange(10)
print(x)
print('Where should 5 be inserted?: ', np.searchsorted(x, 5))
print('Where should 5 be inserted (right)?: ', np.searchsorted(x, 5, side='right'))

[0 1 2 3 4 5 6 7 8 9]
Where should 5 be inserted?:  5
Where should 5 be inserted (right)?:  6


In [257]:
# Create a 1D array
x = np.arange(5)
print('Original array: ', x)

# Introduce a new column axis
x_col = x[:, np.newaxis]
print('x_col shape: ', x_col.shape)
print(x_col)

# Introduce a new row axis
x_row = x[np.newaxis, :]
print('x_row shape: ', x_row.shape)
print(x_row)

Original array:  [0 1 2 3 4]
x_col shape:  (5, 1)
[[0]
 [1]
 [2]
 [3]
 [4]]
x_row shape:  (1, 5)
[[0 1 2 3 4]]


In [264]:
# Create the array and bins
x = np.random.randint(1,10, size=10)
print(x)
bins = np.array([0, 3, 6, 9])

# Get bin allotments
np.digitize(x, bins)

[6 2 6 2 4 8 4 6 6 1]


array([3, 1, 3, 1, 2, 3, 2, 3, 3, 1], dtype=int64)

In [265]:
# Cap all elements of x to lie between 3 and 8
np.clip(x, 3, 8)

array([6, 3, 6, 3, 4, 8, 4, 6, 6, 3])

In [267]:
# Bincount example
x = np.array([1,1,2,2,2,4,4,5,6,6,6]) # doesn't need to be sorted
print(np.bincount(x)) # 0 occurs 0 times, 1 occurs 2 times, 2 occurs thrice, 3 occurs 0 times, ...

# Histogram example
counts, bins = np.histogram(x, [0, 2, 4, 6, 8])
print('Counts: ', counts)
print('Bins: ', bins)

[0 2 3 0 2 1 3]
Counts:  [2 3 3 3]
Bins:  [0 2 4 6 8]
