In [5]:
# 1. Import numpy as np and see the version
import numpy as np
np.version.version

'1.16.4'

In [9]:
# 2. How to create a 1D array? Create a 1D array of numbers from 0 to 9
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
# 3. How to create a boolean array? Create a 3×3 numpy array of all True’s
arr2d = np.ones((3,3), dtype=bool)
print(arr2d)

# Alternate method
print(np.full((3, 3), True, dtype=bool))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [14]:
# 4. How to extract items that satisfy a given condition from 1D array? Extract all odd numbers from arr

arr = np.arange(10)
print(np.where(arr %2 == 1))

(array([1, 3, 5, 7, 9], dtype=int64),)


In [15]:
# 5. How to replace items that satisfy a condition with another value in numpy array? Replace all odd numbers in arr with -1
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [21]:
# 6. How to replace items that satisfy a condition without affecting the original array? Replace all odd numbers in arr with -1 without changing arr
arr = np.arange(10)
arr_copy = np.copy(arr)
print(arr_copy)
print(arr)
arr_copy[arr_copy % 2 == 1] = -1
print(arr_copy)

# Alternate Method

out = np.where(arr % 2 == 1, -1, arr)
print(arr)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [24]:
# 7. How to reshape an array? Convert a 1D array to a 2D array with 2 rows
arr = np.arange(10)
arr2d = np.reshape(arr, (2,5))
arr2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [37]:
# 8. How to stack two arrays vertically? Stack arrays a and b vertically

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a)
print(b)
print("---------------------")
# Method 1
print(np.concatenate([a,b], axis=0))
print("---------------------")
# Method 2
print(np.vstack((a,b)))
print("---------------------")
# Method 3
print(np.r_[a,b])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
---------------------
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
---------------------
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
---------------------
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [38]:
# 9. How to stack two arrays horizontally?
# Method 1
print(np.concatenate([a,b], axis=1))
print("---------------------")
# Method 2
print(np.hstack((a,b)))
print("---------------------")
# Method 3
print(np.c_[a,b])

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
---------------------
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
---------------------
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [40]:
# 10. How to generate custom sequences in numpy without hardcoding? 
# Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
# Input : a = np.array([1,2,3])`
# Output : array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
a = np.array([1,2,3])
np.r_[np.repeat(a,3), np.tile(a,3)]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [41]:
# 11. How to get the common items between two python numpy arrays?
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


In [47]:
# 12. How to remove from one array those items that exist in another? From array a remove all items present in array b
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(np.setdiff1d(a,b))

[1 2 3 4]
